export const QUESTION_GET_START = 'QUESTION_GET_START';
export const QUESTION_GET_SUCCESS = 'QUESTION_GET_SUCCESS';
export const QUESTION_GET_FAIL = 'QUESTION_GET_FAIL';

export const ANSWER_GET_START = 'ANSWER_GET_START';
export const ANSWER_GET_SUCCESS = 'ANSWER_GET_SUCCESS';
export const ANSWER_GET_FAIL = 'ANSWER_GET_FAIL';

export const TRACKS_GET_START = 'TRACKS_GET_START';
export const TRACKS_GET_SUCCESS = 'TRACKS_GET_SUCCESS';
export const TRACKS_GET_FAIL = 'TRACKS_GET_FAIL';

export const POINTS_GET_START = 'POINTS_GET_START';
export const POINTS_GET_SUCCESS = 'POINTS_GET_SUCCESS';
export const POINTS_GET_FAIL = 'POINTS_GET_FAIL';

export const SCORE = 'SCORE';
